# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set the working directory   
 in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app   


# Upgrade pip and install dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run your app
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]