apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llm
spec:
  serviceUnhealthySecondThreshold: 9000 # Config for the health check threshold for Ray Serve applications. Default value is 900.
  deploymentUnhealthySecondThreshold: 3000 # Config for the health check threshold for Ray dashboard agent. Default value is 300.
  serveConfigV2: |
    applications:
      - name: llm
        import_path: serve:llm_app
        runtime_env:
          working_dir: "https://USER:SECRET@github.com/CARIAD-T1/ude-nli-services/archive/refs/tags/v1.0.1-pre.zip"
          pip:
            - "sqlparse"
            - "fastapi"
            - "qdrant-client"
            - "pydantic"
            - "ctransformers"
            - "ctransformers[cuda]"
  rayClusterConfig:
    rayVersion: '2.9.0' # Should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      # Pod template
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.9.0-py310-gpu
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
            resources:
              limits:
                cpu: "4"
                memory: "64G"
                nvidia.com/gpu: 1
              requests:
                cpu: "4"
                memory: "32G"
                nvidia.com/gpu: 1
          volumes:
            - name: ray-logs
              emptyDir: {}
    workerGroupSpecs:
    # The pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 2
      groupName: gpu-group
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray-ml:2.9.0-py310-gpu
            resources:
              limits:
                cpu: 4
                memory: "64G"
                nvidia.com/gpu: 1
              requests:
                cpu: 4
                memory: "32G"
                nvidia.com/gpu: 1
          # Please add the following taints to the GPU node.
          tolerations:
            - key: "ray.io/node-type"
              operator: "Equal"
              value: "worker"
              effect: "NoSchedule"

